name: sunlife-bmi-2026-sli

services:
  app:
    image: rasyabent/sunlife-bmi-2025_sli:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    build: !reset null
    networks:
      - internal
      - web

  migrate:
    image: rasyabent/sunlife-bmi-2025_sli-migrate:latest
    env_file:
      - .env
    build: !reset null
    networks:
      - internal
